### ISSUE TITLE
Unused import warnings

### ISSUE THREAD

**Issue by matthewpflueger** [shadaj/slinky#109]
I've recently upgraded to 0.3.0 and am receiving a lot of unused import warnings for Component and StatelessComponent. It looks like when the macro expands no reference remains of Component/StatelessComponent. Any chance we can correct this?

Minus the warnings, everything works fine with 0.3.0 in my small app!

**Comment by shadaj** [comment]
I think this can definitely be addressed! Because we now reuse the existing class as the definition class, the `extends Component/StatelessComponent` is being eliminated. I think the easiest fix will probably be to introduce some dummy element that references the original `Component` type.
