### ISSUE TITLE
Support for higher order components

### ISSUE THREAD

**Issue by hejfelix** [shadaj/slinky#139]
I'm struggling to implement https://reacttraining.com/react-router/web/api/withRouter
It seems like we need support for some kind of higher order components to succeed here.

**Comment by shadaj** [comment]
@hejfelix can you try using `ReactComponentClass` as a props type for `withRouter` as per https://slinky.shadaj.me/docs/external-components/ ? That method has worked for other higher order components like Apollo.

**Comment by hejfelix** [comment]
I tried something like that with no success -- I'll give it another go and return here with the results + some code

**Comment by hejfelix** [comment]
Right, so I tried some stuff:

```scala
@JSImport("react-router", JSImport.Default)
@js.native
object ReactRouter extends js.Object {
  val withRouter: js.Function1[ReactComponentClass,ReactComponentClass] = js.native
}
```

There's my withRouter def. When I try to use it:

```scala
    val clazz: ReactComponentClass = withRouter(Demos)
    val element = div(withRouter(Demos))
    ReactDOM.render(element, container)
```

which yields 

> [error] /Users/dkfepaha/repos/slinky-wrappers/demo/src/main/scala/com/lambdaminute/slinkywrappers/web/Main.scala:37:19: overloaded method value apply with alternatives:
> [error]   (elems: slinky.core.facade.ReactElement*)slinky.core.facade.ReactElement <and>
> [error]   (mod: slinky.core.AttrPair[slinky.web.html.div.tag.type],remainingMods: slinky.core.AttrPair[slinky.web.html.div.tag.type]*)slinky.core.WithAttrs
> [error]  cannot be applied to (slinky.core.ReactComponentClass)
> [error]     val element = div(withRouter(Demos))
> [error]                   ^
> [error] one error found
> [error] (demo / Compile / compileIncremental) Compilation failed
> [error] Total time: 5 s, completed May 14, 2018 12:50:19 PM

I also tried to apply the ReactComponentClass instance:

```scala
    val clazz: ReactComponentClass = withRouter(Demos)
    val element = div(withRouter(Demos).apply())
    ReactDOM.render(element, container)
```

but that also doesn't work:

> [error] /Users/dkfepaha/repos/slinky-wrappers/demo/src/main/scala/com/lambdaminute/slinkywrappers/web/Main.scala:37:41: value apply is not a member of slinky.core.ReactComponentClass
> [error]     val element = div(withRouter(Demos).apply())
> [error]                                         ^
> [error] one error found
> [error] (demo / Compile / compileIncremental) Compilation failed
> [error] Total time: 6 s, completed May 14, 2018 12:52:20 PM

**Comment by hejfelix** [comment]
Are you saying I should treat `withRouter` as a component?

**Comment by hejfelix** [comment]
Right, so tried to model it as a component:

```scala
@JSImport("react-router", JSImport.Default)
@js.native
object ReactRouter extends js.Object {
  val withRouter: js.Object = js.native
}

@react object withRouter extends ExternalComponent {
  override type Props = ReactComponentClass
  override val component = ReactRouter.withRouter
}
```

And this compiles with client code:
```
    val element = withRouter(Demos)
    ReactDOM.render(element.apply(), container)
```

However, the javascript console gets me:

> Warning: Functions are not valid as a React child. This may happen if you return a `Component` instead of `<Component />` from render. Or maybe you meant to call this function rather than return it.
>     in withRouter

**Comment by hejfelix** [comment]
```scala
@JSImport("react-router", JSImport.Default)
@js.native
object ReactRouter extends js.Object {
  val withRouter: js.Function1[ReactComponentClass,js.Function1[js.Object,ReactElement]] = js.native
}
```

This works, however, I would like to give a better guess about the `js.Object` type. I wonder if I can have parameterized methods implemented as `js.native`

**Comment by shadaj** [comment]
@hejfelix so looking at the docs it appears that `withRouter` isn't a React component, which explains the error you got.

For the `RouteProps`, one way you can have it also extract out the `T` values would be to define a custom `Reader` that reads both the default props as well as `T` from the same JS object. Then you could have the component take `type Props = RouteProps[MyExtraType]`. One issue there is that the `ReactComponentClass` is completely untyped so you lose safety there; I'll try to take a look and see if that can be improved.

**Comment by hejfelix** [comment]
Cool, thanks. In case you want to have a look at the current state of my code, here it is:
https://github.com/hejfelix/slinky-wrappers/tree/master/react-router/src/main/scala/com/lambdaminute/slinkywrappers/reactrouter
 
Particularly, you can save the trouble of writing this:

```scala
case class Match(params: js.Object, isExact: Boolean, path: String, url: String)
case class Location(key: UndefOr[String], pathname: UndefOr[String], search: UndefOr[String], hash: UndefOr[String])
case class History(length: Int,
                   action: String,
                   location: Location,
                   push: js.Function,
                   replace: js.Function,
                   go: js.Function,
                   goBack: js.Function,
                   goForward: js.Function,
                   block: js.Function)
case class RouteProps(`match`:Match, location: Location, history: History)
```

**Comment by shadaj** [comment]
Closing because this appears to have been resolved.
