### ISSUE TITLE
Is it possible to export react components to use from native js?

### ISSUE THREAD

**Issue by nihirash** [shadaj/slinky#150]
Does it possible?

Using `@react` annotation doesn't exports definition(and brokes exporting if I've used `@JSExportTopLevel` annoation)

We trying to develop our components with scala.js but all infrastructure are JSX based and we must to export our components as plain-js components. 

Thank you!

**Comment by shadaj** [comment]
Yes, it is! (a bit excited cause this is one of my favorite features of Slinky)

So Slinky components when you define them are Scala objects, but can be converted to regular JS objects through an implicit conversion to the `ReactComponentClass` type. So for example, you could create a JS object containing your exported Slinky components like this:

```scala
js.Dynamic.literal(
  "MyComponent" -> (MyComponent: ReactComponentClass),
  "MyOtherComponent" -> (MyOtherComponent: ReactComponentClass),
  ...
)
```

and then that object would be what you export out of your Scala.js code with `@JSExportTopLevel`.

**Comment by nihirash** [comment]
Thank you! 

That's great! Slinky made our frontend be frontend without pain!
