### ISSUE TITLE
Styled-Components support with Slinky

### ISSUE THREAD

**Issue by Bharat1103** [shadaj/slinky#154]
Hey, 
I am not able to figure out how to directly integrate styled-components into my react components built with Slinky, are there any working examples or templates or snippets for the same ?

**Comment by shadaj** [comment]
I'm working on a wrapper library at https://github.com/shadaj/slinky-styled-components. It's very much a work in progress but does show a basic setup for using it.

**Comment by shadaj** [comment]
`slinky-styled-components` 0.1.0 has been released!

**Comment by evbo** [comment]
@shadaj just curious to hear your thoughts on slinky support for [Linaria](https://github.com/callstack/linaria)?

Still getting introduced, but it seems syntactically similar to styled-components so maybe an easy win for better performance and smaller bundle?
