### ISSUE TITLE
Provide documentation on custom attributes

### ISSUE THREAD

**Issue by baank** [shadaj/slinky#169]
I can't seem to find a section in the documentation that discusses custom attributes e.g.

<a href="xxxx" data-popup="xxxx", data-container = "xxxx">Test</a>

So how to model data-popup and data-container within the a() tag.

**Comment by shadaj** [comment]
x-post from Gitter:

for `data-` attributes, you can write `a(data-"popup" := "xxx")`. For other custom attributes, you can take a look at https://slinky.shadaj.me/docs/custom-tags-and-attributes/
