### ISSUE TITLE
@react macro expansion fails when using traits

### ISSUE THREAD

**Issue by baank** [shadaj/slinky#170]
So I have a component:
@react class MyComponent extends StatelessComponent with MyTrait

This fails to expand with error message:
"@react must annotate a class that extends Component"

**Comment by shadaj** [comment]
I'm marking this as an enhancement since it's not previously supported behavior. I think this can make it in with a 0.5.x release though.

**Comment by DominikGuzei** [comment]
I just ran into the same issue 👍

**Comment by DominikGuzei** [comment]
@shadaj i just tried `0.5.1` and for me this issue has been fixed 🎉

**Comment by shadaj** [comment]
Closing because this has been resolved
