### ISSUE TITLE
Issue when refined type appears in state

### ISSUE THREAD

**Issue by oleg-py** [shadaj/slinky#174]
Hello. I've created a repository to demonstrate the issue:
https://github.com/oleg-py/slinky-refined

Basically, compilation fails if a [refined](https://github.com/fthomas/refined) type appears in state - in props it seems to work fine

**Comment by shadaj** [comment]
@oleg-py small update, looks like you can use `implicitly` to make things work for now

```scala
object App extends ComponentWrapper()(implicitly, implicitly) {
...
}
```

This doesn't handle usage with the `@react` component though, so going to continue looking into this.
