### ISSUE TITLE
Provide support for multiple conditional `className` attribute

### ISSUE THREAD

**Issue by civilizeddev** [shadaj/slinky#191]
## Appreciation
I like slinky. 👍

I would like to give you a suggestion.

## Problem
1. Given an element, `div(className := "ui tab")`
1. When I have a value `isActive: Boolean`, I want it to be like...
    - `div(className := "ui tab")` if `isActive = false`
    - `div(className := "ui tab active")` if `isActive = true`
1. Currently, I have to do this way, and it looks ugly and boring.
    `div(className := "ui tab" + (if (isActive) "active" else ""))`

### 1. Merge all duplicate attributes
- When you write `div(className := "ui tab", className := "active")`, you will finally get
  - **CURRENTLY**: `<div class="active">` (only the last one left)
  - **TO-BE**: `<div class="ui tab active">` (merged)

### 2. Convenience for conditional attributes
There is a similar thing In [japgolly/scalajs-react](https://github.com/japgolly/scalajs-react/blob/master/core/src/main/scala/japgolly/scalajs/react/vdom/HtmlAttrs.scala#L298).

- You can write like this for `<div class="ui tab active">`:
  - `div(className := classSet("ui" -> true, "tab" -> true, "active" -> isActive))`
  - `div(className := classSet1("ui tab", "active" -> isActive))`

Thank you.

**Comment by shadaj** [comment]
I think this could fit well into a `slinky-addons` library that was discussed earlier!

**Comment by shadaj** [comment]
Since this isn't something that will directly fit into Slinky, but instead can be implemented in an independent library, closing.
