### ISSUE TITLE
Consider using standalone plugin for IntelliJ support

### ISSUE THREAD

**Issue by baank** [shadaj/slinky#194]
So I have raised 6 issues against IntelliJ's implementation of library extensions the most concerning being the fact that doesn't actually find Slinky's extension at all. This is with version 0.5.0.

Thoughts on moving this to a standalone plugin or any ideas about potential fixes.

**Comment by gehnaphore** [comment]
https://github.com/shadaj/slinky/pull/212 makes the ijext jar get identified properly as a plugin and loaded properly in 2018.3

**Comment by evbo** [comment]
Is there a link where I can download the Slinky extension library? Intellij `2018.3.2` CE does not auto detect the slinky extension, but intellij gives me the option manually add it under Settings > Languages & Frameworks > Scala > Extensions

**Comment by shadaj** [comment]
`2018.3.2` switched to the new extension detection mechanism, which Slinky doesn't support (yet!). The new system is a lot nicer though, so I'm hoping to get it supported in 0.5.2 and am planning to go with that method of distributing the extension.

**Comment by evbo** [comment]
Thanks @shadaj and good luck with landing 0.5.2! In the meantime, do you happen to know what is the latest version of intellij with slinky support so I can avoid the red? Or, what version do you use? I also tried 2018.1 but that also didn't work

**Comment by shadaj** [comment]
@evbo 2018.2 is what I use (with Slinky 0.5.1). From 0.5.2 onwards 2018.3 will be required.

**Comment by evbo** [comment]
I just tried your extension with 2018.3 and I'm happy to report I can see clearly now with proper syntax highlighting!

**Comment by baank** [comment]
I think we can close this
