### ISSUE TITLE
Support functions as stateless components

### ISSUE THREAD

**Issue by a1russell** [shadaj/slinky#199]
I think it'd be a good idea as an enhancement to the `@react` annotation, to support functions as stateless components. Once [React hooks](https://github.com/reactjs/rfcs/blob/hooks-rfc/text/0000-react-hooks.md) make it into a stable release, the usage of functions as components could begin to outpace that of classes as components. In the end, I think this will eventually be needed for the project to stay true to its description: "Write Scala.js React apps just like you would in ES6."

**Comment by shadaj** [comment]
https://github.com/shadaj/slinky-hooks!

**Comment by a1russell** [comment]
Awesome! Is there an example anywhere to see them in action?
