### ISSUE TITLE
Defining intialState with parens leads to cryptic runtime errors and application crash

### ISSUE THREAD

**Issue by gavares** [shadaj/slinky#204]
Slinky version: 0.5.1

When defining a component with state, defining the `initialState` override with parens leads to a cryptic ClassCastException that type "anonymous() is not an instance of MyComponent$State". Removing parens from the definition of `initialState` resolves the issue.  

The runtime error does not happen until the first attempt is made at accessing the `state` var inside the component.

This works:
```scala
override def initialState = State()
```

This does not:
```scala
override def intiialState() = State()
````

Catching this error at compile time would be ideal. If that's not possible, a note in the documentation would likely help others that come across this issue.

**Comment by shadaj** [comment]
This has reappeared due to a Scalafix rule removing the extra parentheses in our test.

**Comment by shadaj** [comment]
Looks like adding the extra parentheses just causes a compilation error on Scala 2.13, so marking as won't fix since this isn't possible anymore.
