### ISSUE TITLE
ExternalComponent ReactTable class results in Error: Element type is invalid

### ISSUE THREAD

**Issue by evbo** [shadaj/slinky#215]
Trying my best to follow the `ExternalComponent` [docs](https://slinky.shadaj.me/docs/external-components/) and a [couple](https://github.com/schwepp/slinky-native-example/blob/master/src/main/scala/hello/world/react.scala) examples, I'm ending up with error:

```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

Here's my attempted implementation:

```
@JSImport("react-table", JSImport.Default)
@js.native
object ReactTableLibrary extends js.Object {
  val ReactTable: js.Object = js.native
}

@react object ReactTable extends ExternalComponent {
  case class Props(data: js.Array[js.Dictionary[js.Any]], columns: js.Array[js.Dictionary[js.Any]])
  override val component = ReactTableLibrary.ReactTable
}
```

The [object I'm trying to use ](https://github.com/react-tools/react-table/blob/master/src/index.js#L12) is a class that extends `Methods(Lifecycle(Component))`. Is slinky only able to import classes that extend react component?

**Comment by shadaj** [comment]
@evbo this looks like an issue with how you're importing the component. Your component reference should directly be `ReactTableLibrary`, since the component is the default export of the module.

**Comment by evbo** [comment]
Thank you. That was it.

Sort of related question: Do you have any recommendations for how a newcomer to javascript could debug this issue? One of the major benefits to scala.js is catching issues like this at compile time, but this type of error isn't caught until runtime. Is there something I could be doing to catch this error sooner?
