### ISSUE TITLE
Include SyntheticEvent classes

### ISSUE THREAD

**Issue by baank** [shadaj/slinky#228]
When trying to wrap external components often you see SyntheticEvent types.

It would be nice if this file was included:

https://github.com/xored/scala-js-react/blob/master/scalajs-react/src/main/scala/com/xored/scalajs/react/event/SyntheticEvent.scala

**Comment by shadaj** [comment]
I'm planning on including this with the 0.6.0 tags API improvements!

**Comment by shadaj** [comment]
Fixed by #243
