### ISSUE TITLE
Add React 16 Support for GetDerivedStateFromProps

### ISSUE THREAD

**Issue by evbo** [shadaj/slinky#229]
For the particular use case of fetching data when a component's Props change (e.g. due to a parent component updating them), it looks like the recommended function for that is `GetDerivedStateFromProps` as an alternative to the unsafe `componentWillReceiveProps` lifecycle:

https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#fetching-external-data-when-props-change

> the componentWillReceiveProps lifecycle is often mis-used in ways that do present problems. Because of this, the method will be deprecated

I noticed slinky documents [full support for React 16](https://github.com/shadaj/slinky/blob/master/CHANGELOG.md#highlights), so I thought I'd point this out as it appears missing from `Component`

**Comment by shadaj** [comment]
`getDerivedStateFromProps` is static, so it goes into the companion object. See the "Static Lifecycle Methods section of https://slinky.shadaj.me/docs/writing-components/ for more details!

**Comment by evbo** [comment]
doh!
