### ISSUE TITLE
GetDerivedStateFromProps types and their meaning

### ISSUE THREAD

**Issue by evbo** [shadaj/slinky#230]
Hi, 3 questions, all of which related to `getDerivedStateFromProps(nextProps, prevState)`:

1. What should `getDerivedStateFromProps` return if there are no changes?

1. and why doesn't `getDerivedStateFromProps` return `Option[State]`?

1.  `Props` in one of my `@react` classes has attributes with nested types (e.g.  `Props(a: A[B[C]])`) but Intellij syntax highlighting purports `nextProps.a` has type: `Any` if imported like below (see bottom of this issue). Actual type issues don't occur at compile/run time.

Context:
According to [react docs](https://reactjs.org/docs/react-component.html#static-getderivedstatefromprops), `GetDerivedStateFromProps` should return `null` if there are no changes in state.

My instincts tell me that means the return type should be `Option[State]` right? In any case, I searched this repo and [saw null returned instead like](https://github.com/shadaj/slinky/blob/bd0adafaeafa8db51916b7db756d17b6ea3edd66/core/src/main/scala/slinky/core/BaseComponentWrapper.scala#L46): `null.asInstanceOf[State]`

But when I return `null` like that it actually sets my state to null and then I get null pointer the next time render is called, which accesses state attributes.
`TypeError: "b" is null`

So I've instead been returning `prevState` if there are no changes - is that the current best practice in slinky?

```scala
// first import the package contents
import package.containing.aliases.TypeAliases
// Note: syntax highlighting works fine if here I instead do: import package.containing.aliases.TypeAliases._

object Companion {
  // "TypeAliasses" is an object inside "aliases" containing the types A, B, C
  import TypeAliases._

  override def getDerivedStateFromProps(nextProps: Props, prevState: State): State = {
    if (nextProps.a != prevState.a) {
      prevState.copy(
        b = nextProps.a.b
      )
    } else {
     // ideally wouldn't we return None here? I tried null.asInstanceOf[State] but that gave NPE
      prevState
    }
  }
}
```

**Comment by shadaj** [comment]
Just took a look at the React docs, they also say that users can return `null` to not update the state, so that's definitely something Slinky should handle. I'm not super sure about changing the return type to `Option[State]` though because this would add a bunch of extra code to wrap the return value in `Some` with reduced benefits because the optional result is not reachable from any other Scala code.

**Comment by evbo** [comment]
Yes, and I did return null, but did you see the part I wrote on what happened by doing so?:
>But when I return `null` like that it actually sets my state to null and then I get null pointer the next time render is called, which accesses state attributes.
`TypeError: "b" is null`

From what I could tell, it's not following the usual process of skipping render, and the state is actually getting set to null instead of just not being updated (unless I've done something horribly wrong and not realized it!)

**Comment by shadaj** [comment]
Yeah, that's what I need to fix with Slinky not handling null return values correctly.
