### ISSUE TITLE
[not code related] Slinky docs have dead pages

### ISSUE THREAD

**Issue by evbo** [shadaj/slinky#232]
Started researching functional components in react using slinky and this was the first hit on google:

https://slinky.shadaj.me/docs/functional-components/

Unfortunately it's a blank page! I eventually found this: https://github.com/shadaj/slinky/blob/master/docs/public/docs/functional-components-and-hooks.md

But wanted you to know since this is impacting your production site

**Comment by evbo** [comment]
ok, so I just realized support for hooks is brand new so understandable the docs are still catching up with the code: https://github.com/shadaj/slinky/pull/227

I noticed you merged into master just very recently, so understandable to docs are still catching up with the code. Coincidentally a day later I am continuing my learning of react with functional components! Thank you for building the stairs as I march on them!

I'll give this a whirl: `"me.shadaj" %%% "slinky-core" % "0.5.2+6-10d43572"`

**Comment by shadaj** [comment]
I decided not to push up the docs to the main site, since it might be confusing to see docs for unreleased features. The docs for functional components are instead available at https://5c6d19c904cca70008c477f3--slinky.netlify.com/docs/functional-components-and-hooks/
