### ISSUE TITLE
Intellij Syntax Hightlighting Seemingly not correct

### ISSUE THREAD

**Issue by evbo** [shadaj/slinky#233]
Hi, just checking out the latest and greatest (`0.5.2+6-10d43572`) and noticed Intellij syntax highlighting odd behaviors:

For the following:

```scala
@JSImport("rc-slider/lib/Slider", JSImport.Default)
@js.native
object Slider extends js.Object {
}

@react object ReactSlider extends ExternalComponent {
  case class Props(
                    defaultValue: Double,
                    value: Double,
                    disabled: Boolean,
                    min: Double,
                    max: Double,
                    step: Int
                  )
  override val component = Slider
```

Intellij purports that I need to call the object like so:

```scala
ReactSlider(
                      ReactSlider.Props(
                          defaultValue = 5.0,
                          value = 5.0,
                          disabled = false,
                          min = 0.0,
                          max = 300.0,
                          step = 5
                      )
            )
```

If I don't explicitly set `Props` argument, I get `Reassignment to val` error and lots of red.

Also, the following:

```scala
div(
          sharedState.Consumer{ stuff =>
            ApolloProvider(stuff.client)(
              div(
                ReactSlider(...)
              )
            )
          }
        )
```

Is riddled with "type mismatches" (claiming that `ReactElement` isn't being returned even though it is) when really there are none.

However, none of these are true errors and everything runs fine if I ignore that error

**Comment by evbo** [comment]
Interestingly these problems **all** go away if I Invalidate Caches and Restart in Intellij.

So it's repeatable, but avoidable as well! Basically you have to make sure **never** to click `Import Changes` pop up and I leave `Auto-Import` off.

**Comment by shadaj** [comment]
Could you share the code that results in the `Reassignment to val` error? I tested locally and things seemed to work fine. For the second two, those look like they may be some weird interaction with an IntelliJ bug, so I'll have to dig a bit deeper.

**Comment by evbo** [comment]
Sure, and forgive me but I can't seem to reproduce the _exact_ syntax highlighting error for the first bullet above but it's effectively the same end result: `Cannot resolve symbol ` followed by prop name. 

As before, if I instead construct the component without keyword args, or explicitly construct props it works without highlighted errors (`TestFunct(TestFunc.Props(first = "f", second = 1))`)

```

import org.scalajs.dom
import slinky.core.FunctionalComponent
import slinky.core.annotations.react
import slinky.web.ReactDOM
import slinky.web.html.div

import scala.scalajs.js.annotation.{JSExportAll, JSExportTopLevel}


@react object TestFunc {
  case class Props(first: String, second: Int)

  val component = FunctionalComponent[Props] { props =>
    div(s"${props.first} ${props.second}")
  }
}


@JSExportTopLevel(name="entrypoint") @JSExportAll
object Entry{

  def main(args: Array[String]): Unit = {
    ReactDOM.render(AppTest.main(), dom.document.getElementById("root"))
  }
}


object AppTest {

  type Props = Unit

  val main = FunctionalComponent[Props] { _ =>
    div(
      TestFunc(first = "f", second = 1)
    )
  }
}
```


Perhaps it was saying `Reassignment to val` before instead of `Cannot resolve symbol` due to how my source code files were organized. Not sure though, I'm far from a Jet Brain specialist!

**Comment by evbo** [comment]
just tested on slinky `0.6.0` and `reassignment to val` issues still present

**Comment by evbo** [comment]
Another syntax highlighting issue that popped up today is when I use scalajs either expression for a type:

```scala
@JSImport("react-csv", "CSVLink")
@js.native
object CSVLink extends js.Object

@react object CsvDownloadLink extends ExternalComponentWithRefType[CsvLinkRef] {
  case class Props(
                    data: js.Array[js.Object] | String,
                    filename: String,
                    separator: String = "\t",
                    target: String = "_blank"
                  )
  override val component = CSVLink
}
```

If I instantiate this with a `String` for `data`, it works fine and there are no syntax errors, but instantiating with `data` as a `js.Array[js.Object]` generates syntax error even though the code compiles and runs just fine:
```
Expression of type Array[Object] doesn't conform to expected type Array[Object] | String
```

**Comment by shadaj** [comment]
@evbo thanks for the reports, I'll try to take a look at them soon (might not get to this for 2ish weeks since I have finals 😢 ). As far as I remember, IntelliJ generally has trouble with Scala.js union types. Does IntelliJ still complain if the `@react` annotation is not used?

**Comment by evbo** [comment]
@shadaj good question, if I remove the `@react` the syntax error changes to the one I was seeing before: `reassignment to val`

**Comment by baank** [comment]
@shadaj  .. I can provide more examples of where union types fall apart:

```
@react object Orange extends ExternalComponent {
  case class Props(param1: Double | Int, param2: Seq[Double | Int])
}

# Works
Orange(param1 = 5)

# IntellIJ will be underline param2 as being invalid with the following message:
# Expected: Seq[Double | Int], Actual: Seq[Int]
Orange(param2 = Seq(5))
```

**Comment by evbo** [comment]
If the above problems are IntelliJ it wouldn't surprise me. However, in Slinky `0.6.2` I'm getting another interesting IntelliJ warning when I try creating a function that returns a component as a generic `ReactElement` (I just need jsx):

```scala
val component: ReactElement = (props: PropsType) => TheComponent(...)
```

> fruitless type test: a value of type PropsType => TheComponent.component.Result cannot also be PropsType => ReactElement(but still might match its erasure)

I think this warning is completely valid, but I'm not sure what to do about the warning. If I instead try to be more specific with its type, I can no longer get it to compile:

```scala
type ReturnComponent = PropsType => TheComponent.component.Result
val component: ReturnComponent = (props: PropsType) => TheComponent(...)
```

gives error:

> type mismatch;
[error]  found   : TheComponent.component.Result
[error]     (which expands to)  slinky.core.KeyAddingStage
[error]  required: ReturnComponent
[error]     (which expands to)  PropsType => slinky.core.KeyAddingStage


So I'm fine ignoring the warning as valid, but ideally a warning has a fix. Is there a type safe way in this case? I've tried returning `TheComponent(...).withKey("some key")` but still get the same error.

**Comment by baank** [comment]
I may be wrong about my understanding but the first example doesn't look correct. You aren't returning a ReactElement but instead returning a component. If you were to return TheComponent.render() it would be a ReactElement.

The second example looks sort of right although not sure if Slinky understands the case class. Any reason you wouldn't just rely on type inference ?

**Comment by shadaj** [comment]
So, when writing functional components you need to wrap the function in `FunctionalComponent` so that Slinky transforms the function into a component instead of just leaving it as a regular Scala function. IntelliJ should then pick up that you are defining a functional component and generate the appropriate `apply` methods.

**Comment by evbo** [comment]
here's how to reproduce in IntelliJ IDEA 2019.1: `idea-IC-191.6183.87`

```scala
@react object TheComponent  {
  case class Props(stuff: Int)
  val component = FunctionalComponent[Props] { props => 
    div("div")
  }
}

type ReturnComponent = Int => ReactElement

for {
  a <- Some("")
  funcThatGivesComponent: ReturnComponent = (someInt: Int) => TheComponent(  // warning given here
    someInt
  )
} yield "result"
```

Javascript frameworks can require you to pass the external components functions that can produce new components, with some argument (`someInt`) allowing you to customize the component. For instance, "react table" does this a lot.

**Comment by evbo** [comment]
given how old this issue is and the code example I once had is totally gone now (react table has since migrated to hooks) I recommend closing this issue since no other comments concur my findings.

this is probably and hopefully old news ;)
