### ISSUE TITLE
Does Slinky support transistive dependencies?

### ISSUE THREAD

**Issue by evbo** [shadaj/slinky#234]
Hi, this might be an expected scalaJs requirement in writing facades (so sorry in advance but I didn't see [documentation on it](https://www.scala-js.org/doc/interoperability/facade-types.html)), but is it necessary in Slinky to write facades for _dependencies_ of a Javascript library if your scala code never directly interfaces with them?

For instance, I added a [facade for rc-slider](https://www.npmjs.com/package/rc-slider) (it itself has 7 dependencies), which optionally can specify a custom "handle" (to produce a tooltip). But when I enabled this, suddenly I needed to define `ExternalComponent` objects for a few dependencies I'm otherwise not directly needing:
- rc-tooltip
- rc-align
- rc-trigger

So even though `rc-slider` is the only external object I'm actually constructing in **my** code, the following is necessary to avoid type errors, which I guess is because Scala code is first being auto generated for me involving these types before being compiled into javascript?

Is there no way to avoid defining Scala types for Javascript dependencies you have no intention of directly writing Scala code with?

To give you an idea, from the comment below down is the extra boilerplate I needed for everything to work without errors:
```scala
@JSImport("rc-slider/lib/Slider", JSImport.Default)
@js.native
object Slider extends js.Object {
  val Handle: js.Object = js.native
}

@react object RcSlider extends ExternalComponent {
  case class Props(
                    defaultValue: Double,
                    value: Double,
                    disabled: Boolean,
                    min: Double,
                    max: Double,
                    step: Int,
                    onChange: Double => Unit,
                    marks: js.Object,
                    tipFormatter: Double => String,
                    handle: HandleProps => ReactElement
                  )
  override val component = Slider
}

@react object RcHandle extends ExternalComponent {
  case class Props(
                    value: ReactElement
                  )
  override val component = Slider.Handle
}

// additional facades for dependencies of rc-slider (that I'm not directly using in my scala code)
@JSImport("rc-tooltip", JSImport.Default)
@js.native
object Tooltip extends js.Object {}

@react object RcTooltip extends ExternalComponent {
  case class Props(
                    placement: String,
                    trigger: Seq[String],
                    overlay: ReactElement,
                    visible: Boolean,
                    key: Int
                  )
  override val component = Tooltip
}

@JSImport("rc-align", JSImport.Default)
@js.native
object Align extends js.Object {}


@react object RcAlign extends ExternalComponent {
  case class Props(align: AlignConfig)
  override val component = Align
}

@JSImport("rc-trigger", JSImport.Default)
@js.native
object Trigger extends js.Object {}

@react object RcTrigger extends ExternalComponent {
  case class Props(
                  action: Seq[String],
                  popup: ReactElement,
                  popupAlign: AlignConfig
                  )
  override val component = Trigger
}
```

**Comment by shadaj** [comment]
Hi, what is the error you get if you don't define the additional facades? Everything should have worked fine without having to define the transitive dependency types.

**Comment by evbo** [comment]
I conflated two issues after getting confused by javascript console errors. You're right my added facades were not needed.

Sorry about that! Javascript console errors can really throw me off sometimes
