### ISSUE TITLE
hot reloading issue when debugging implicit conversions to javascript types

### ISSUE THREAD

**Issue by evbo** [shadaj/slinky#236]
The following works for defining [the argument in this function](https://github.com/tannerlinsley/react-table/blob/v6/src/defaultProps.js#L226):
```
@JSGlobal
@js.native
class CellInfo(val columns: js.Object, val onChange: js.Function1[Double, js.Any]) extends ReactElement

object CellInfo {
  type FilterUpdate = js.UndefOr[js.Function1[CellInfo, ReactElement]]
}
```

But if I try to consistently use scala function types ( `=>`) instead of the `js` ones, I get:
```
uncaught exception: scala.scalajs.runtime.UndefinedBehaviorError: An undefined behavior was detected: function onChange(value) {
              return _this2.filterColumn(column, value);
            } is not an instance of scala.Function1
```

Similarly, if I try to use `Option` instead of `js.UndefOr` I get:

```
Warning: Failed prop type: Invalid prop `columns[0].Filter` supplied to `ReactTable`

Error: Objects are not valid as a React child (found: object with keys {f$2}). If you meant to render a collection of children, use an array instead.
```

I use `Option` and `=>` in defining other js types. Any reason why they shouldn't work here in place of `UndefOr` and `Function1`?

**Comment by evbo** [comment]
Also, forgive me if this is a separate issue (related to hot swapping or maybe it has nothing to do with slinky?!) but since I've only noticed it while working with the `type` described above I'll post here:

 I'm noticing that code changes are sometimes cached (hot swapping isn't always running the latest code). I've repeatedly tried emptying the firefox cache to ensure my browser isn't holding on to outdated code, and so I'm convinced something running in Intellij (`slinky-hot`/`scalajs-bundler`/`sbt`?) is caching old code in `target` because changes are only getting reflected after I stop webpack dev server, delete `target` directory, and then start it again (defeating the purpose of hot reloading)

Following my procedure above, if I start with the following code it compiles and resolve the js function `onChange`:
```
@JSGlobal
@js.native
class CellInfo(val columns: js.Object, val onChange: js.Function1[Double, js.Any]) extends ReactElement
```

However, as discussed above if I change it to the following I get the `not an instance of Function1` exception:
```
@JSGlobal
@js.native
class CellInfo(val columns: js.Object, val onChange: Double => js.Any) extends ReactElement
```

Then, if I switch the code back to using the `Function1` I still get the same error! The only way to fix it is to break the cache by deleting my `target` or change the code as follows:

```
@JSGlobal
@js.native
class CellInfo(val columns: js.Object, val onChange: js.Function1[js.Any, js.Any]) extends ReactElement
```

Then my calling code needs to run the function like `onChange(js.Any.fromDouble(x))` and I presume the cache is invalidated so it works again!

Once it's working, I change the code back to original (using `Double` type instead of `js.Any`) and it stays working (as long as I stay using `Function1`).

Really confused how code is getting cached and I'm not sure where but hoping you might have experienced something like this before! Do you think slinky hot reloading has anything to do with this? Or does scalajs-bundler override hot reloading (in which case maybe I should reach out to them)?

**Comment by shadaj** [comment]
Hi @evbo! Since you're defining `CellInfo` as a `@js.native` facade, all the types inside also need to be JS types, which is why it's only working with `js.Function1`. In this case, looks like the definition of `FilterComponent` is meant to be used as a component, so it would be best to wrap it in an `ExternalComponent` whose `Props` type can use Scala types since Slinky handles the conversion to JS. In addition, using an `ExternalComponent` will enable React to properly diff the tree, since treating the component as a function effectively inlines it into the parent.

**Comment by shadaj** [comment]
On the hot-loading, there are definitely some rough edges around when the type definition changes. I'm hoping to work on cleaning up the logic behind that after 0.6.0 is released.

**Comment by evbo** [comment]
ok, so that this issue is more useful to you I've changed the title to indicate hot-reloading

Also I'm glad you're already aware! Maybe it's good I also share that I get the following error after hot reloading several times. It eventually causes me to restart from a fresh build:

```
[error] Metaspace
[error] java.lang.ClassLoader.defineClass1(Native Method)
[error] java.lang.ClassLoader.defineClass(ClassLoader.java:763)
[error] java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[error] java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
[error] java.net.URLClassLoader.access$100(URLClassLoader.java:73)
[error] java.net.URLClassLoader$1.run(URLClassLoader.java:368)
[error] java.net.URLClassLoader$1.run(URLClassLoader.java:362)
[error] java.security.AccessController.doPrivileged(Native Method)
[error] java.net.URLClassLoader.findClass(URLClassLoader.java:361)
[error] java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error] java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error] org.scalajs.core.compiler.ScalaJSPlugin$jsAddons$.jsDefinitions$lzycompute$1(ScalaJSPlugin.scala:47)
[error] org.scalajs.core.compiler.ScalaJSPlugin$jsAddons$.jsDefinitions(ScalaJSPlugin.scala:47)
[error] org.scalajs.core.compiler.JSPrimitives.$anonfun$initWithPrimitives$1(JSPrimitives.scala:93)
[error] org.scalajs.core.compiler.JSPrimitives$$Lambda$17392/948066115.apply$mcVI$sp(Unknown Source)
[error] scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
[error] org.scalajs.core.compiler.JSPrimitives.initWithPrimitives(JSPrimitives.scala:92)
[error] org.scalajs.core.compiler.JSPrimitives.initPrepJSPrimitives(JSPrimitives.scala:69)
[error] org.scalajs.core.compiler.PrepJSInterop$JSInteropPhase.run(PrepJSInterop.scala:63)
[error] scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1498)
[error] scala.tools.nsc.Global$Run.compileUnits(Global.scala:1482)
[error] scala.tools.nsc.Global$Run.compileSources(Global.scala:1475)
[error] scala.tools.nsc.Global$Run.compile(Global.scala:1598)
[error] xsbt.CachedCompiler0.run(CompilerInterface.scala:131)
[error] xsbt.CachedCompiler0.run(CompilerInterface.scala:106)
[error] xsbt.CompilerInterface.run(CompilerInterface.scala:32)
[error] sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
[error] sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] java.lang.reflect.Method.invoke(Method.java:498)
[error] sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:111)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:90)
[error]            
[error] java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Metaspace
[error]         at java.util.concurrent.FutureTask.report(FutureTask.java:122)
[error]         at java.util.concurrent.FutureTask.get(FutureTask.java:192)
[error]         at sbt.ConcurrentRestrictions$$anon$4.take(ConcurrentRestrictions.scala:200)
[error]         at sbt.Execute.next$1(Execute.scala:99)
[error]         at sbt.Execute.processAll(Execute.scala:102)
[error]         at sbt.Execute.runKeep(Execute.scala:79)
[error]         at sbt.EvaluateTask$.liftedTree1$1(EvaluateTask.scala:383)
[error]         at sbt.EvaluateTask$.run$1(EvaluateTask.scala:382)
[error]         at sbt.EvaluateTask$.runTask(EvaluateTask.scala:401)
[error]         at sbt.internal.Aggregation$.$anonfun$timedRun$4(Aggregation.scala:96)
[error]         at sbt.EvaluateTask$.withStreams(EvaluateTask.scala:327)
[error]         at sbt.internal.Aggregation$.timedRun(Aggregation.scala:94)
[error]         at sbt.internal.Aggregation$.runTasks(Aggregation.scala:107)
[error]         at sbt.internal.Aggregation$.$anonfun$applyDynamicTasks$4(Aggregation.scala:170)
[error]         at sbt.Command$.$anonfun$applyEffect$2(Command.scala:121)
[error]         at sbt.internal.Act$.$anonfun$actParser0$3(Act.scala:310)
[error]         at sbt.MainLoop$.processCommand(MainLoop.scala:121)
[error]         at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:105)
[error]         at sbt.State$$anon$1.runCmd$1(State.scala:227)
[error]         at sbt.State$$anon$1.process(State.scala:233)
[error]         at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:105)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.MainLoop$.next(MainLoop.scala:105)
[error]         at sbt.MainLoop$.run(MainLoop.scala:98)
[error]         at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:76)
[error]         at sbt.io.Using.apply(Using.scala:22)
[error]         at sbt.MainLoop$.runWithNewLog(MainLoop.scala:70)
[error]         at sbt.MainLoop$.runAndClearLast(MainLoop.scala:52)
[error]         at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:37)
[error]         at sbt.MainLoop$.runLogged(MainLoop.scala:29)
[error]         at sbt.StandardMain$.runManaged(Main.scala:104)
[error]         at sbt.xMain.run(Main.scala:71)
[error]         at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error]         at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error]         at xsbt.boot.Launch$.run(Launch.scala:109)
[error]         at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error]         at xsbt.boot.Launch$.launch(Launch.scala:117)
[error]         at xsbt.boot.Launch$.apply(Launch.scala:18)
[error]         at xsbt.boot.Boot$.runImpl(Boot.scala:41)
[error]         at xsbt.boot.Boot$.main(Boot.scala:17)
[error]         at xsbt.boot.Boot.main(Boot.scala)
[error] Caused by: java.lang.OutOfMemoryError: Metaspace
[error]         at java.lang.ClassLoader.defineClass1(Native Method)
[error]         at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
[error]         at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[error]         at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
[error]         at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
[error]         at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
[error]         at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
[error]         at java.security.AccessController.doPrivileged(Native Method)
[error]         at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
[error]         at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error]         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error]         at org.scalajs.core.compiler.ScalaJSPlugin$jsAddons$.jsDefinitions$lzycompute$1(ScalaJSPlugin.scala:47)
[error]         at org.scalajs.core.compiler.ScalaJSPlugin$jsAddons$.jsDefinitions(ScalaJSPlugin.scala:47)
[error]         at org.scalajs.core.compiler.JSPrimitives.$anonfun$initWithPrimitives$1(JSPrimitives.scala:93)
[error]         at org.scalajs.core.compiler.JSPrimitives$$Lambda$17392/948066115.apply$mcVI$sp(Unknown Source)
[error]         at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
[error]         at org.scalajs.core.compiler.JSPrimitives.initWithPrimitives(JSPrimitives.scala:92)
[error]         at org.scalajs.core.compiler.JSPrimitives.initPrepJSPrimitives(JSPrimitives.scala:69)
[error]         at org.scalajs.core.compiler.PrepJSInterop$JSInteropPhase.run(PrepJSInterop.scala:63)
[error]         at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1498)
[error]         at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1482)
[error]         at scala.tools.nsc.Global$Run.compileSources(Global.scala:1475)
[error]         at scala.tools.nsc.Global$Run.compile(Global.scala:1598)
[error]         at xsbt.CachedCompiler0.run(CompilerInterface.scala:131)
[error]         at xsbt.CachedCompiler0.run(CompilerInterface.scala:106)
[error]         at xsbt.CompilerInterface.run(CompilerInterface.scala:32)
[error]         at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error]         at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
[error]         at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:111)
[error]         at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:90)
[error] java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Metaspace

```

**Comment by evbo** [comment]
@shadaj also thank you in reference to your earlier point about treating `FilterComponent` as an actual React component. It took me a while to ponder your suggestion, but I ultimately realized the right way to do this (I think!):

My understanding is `FilterComponent` is classified in the React world as a "Stateless Functional Component". The trouble I have is that I want to extend this component to include _additional_ props besides the 3 it expects in the javascript library. So, I actually decided to create a regular `FunctionalComponent`, whereby the first 3 props are of type `Option` so that the Scala code doesn't need to set them at first, but then later on, when the Javascript passes its positional arguments, they get set but my props set by scala are unchanged. It worked and resulted in far less code!

Slinky is very powerful, thank you!

**Comment by evbo** [comment]
@shadaj also thank you for your advice on treating `FilterComponent` like an actual React Component, rather than extending `ReactElement` (which I agree is smelly).

The reason why I'm stuck extending `ReactElement` is because I don't know how in Slinky to _partially apply_ props. In my case, only 1 prop must be sent to the component by the javascript library at runtime: `onChange`, all other props are defined by my scala code.

So I need some way of applying the props my scala code defines, but still handling what the javascript sends, so the only way to model this that I thought of was returning a function, like:

```scala
(e: ReactElement) => {
    ChildComponent(e.onChange, other, props)
}
```

This works! But I agree I'd like to use components. I tried considering your advice, and thought what if my `ChildComponent` has a `onChange` prop but I initialize it to `None`? Then will the javascript library later update it? No, it didn't. Then I thought could my `ExternalComponent` representing the `FilterComponent` have an `onChange` attribute? Not sure how that would work syntactically though.

**Comment by shadaj** [comment]
Ahh, that's an interesting situation. Given how Scala's type system works, I think it would be pretty difficult to express this situation in a type-safe manner with Slinky.

The idea of passing in a function would be the best alternative I think, since to the JS library it'll appear as just a functional component, but in the Scala code you can implement the logic to "redirect" to the component you really want to render.

**Comment by evbo** [comment]
@shadaj Unless you think it's valuable keeping this issue open due to the hot reloading problem, I am fine closing this issue.

The "interesting situation" I think is already being captured in this issue, as the workaround I'm using applies to both: https://github.com/shadaj/slinky/issues/240

**Comment by shadaj** [comment]
Yes, I'll close this since.
