### ISSUE TITLE
Passing Seq of FunctionalComponents as children causes React warning

### ISSUE THREAD

**Issue by evbo** [shadaj/slinky#239]
In order to conditionally set children, I'm getting warnings in the console when I use a collection rather than hard coding the children.

This render works (no console warnings):
```scala

        if (condition()) {
            div(className := "row justify-content-around mt-5")(
                child1, 
                child2
             ) 
        } else div(className := "row justify-content-around mt-5")(
              child2
          )
        }
```

But this DRY approach renders with console warning: 

```scala
div(className := "row justify-content-around mt-5")(
        if (condition()) Seq(child1, child2) else Seq(child1)
)
```

`Warning: Each child in a list should have a unique "key" prop.`

The problem with using divs is you need to repeat formatting. So is there a way to pass `Seq[ReactElement]` as children and have that key prop correctly set still?

I tried using [withKey](https://github.com/shadaj/slinky/blob/af7c2f4eeb31d52502e8fda2a4c5d0919fba70f8/docs/public/docs/writing-components.md#writing-components) but I'm using `FunctionalComponents` and for some reason I only see that method for regular components.

**Comment by evbo** [comment]
My baby example really isn't such a big deal. Where this becomes more annoying is when you have _variable_ number of elements. For instance, even though the following _works_ it generates pretty annoying warnings in the console:

```scala
div(className := "btn-group")(
      props.columns.map{ column =>
        button(className := s"btn btn-primary", onClick := toggleSomething _)(
          "seen enough button examples yet?"
        )
      }
    )
```

Hopefully my users can just ignore this for now as I don't know how to work around it... Any quick fixes?
`Warning: Each child in a list should have a unique "key" prop.`

**Comment by shadaj** [comment]
That's really odd, what's the compile error you get when you add `.withKey` right after constructing the functional component?

**Comment by evbo** [comment]
I was never able to "see" `withKey` for `FunctionalComponents`, but that's according to Intellij! So after taking a leap of faith, ignoring syntax highlighted errors, I tried running my app using `withKey` and it worked! 

So it's true for Intellij as well: 

> trust but verify

Intellij in this case purports: `Cannot resolve symbol withKey` for `FunctionalComponents`

I'll add this discrepancy to my list in: https://github.com/shadaj/slinky/issues/233
