### ISSUE TITLE
Prop values of ExternalComponent undefined 

### ISSUE THREAD

**Issue by evbo** [shadaj/slinky#240]
I'm able to get a working facade for [this external component](https://github.com/tannerlinsley/react-table/blob/v6/src/index.js#L12) but with some workarounds I hacked with very little understanding for why they work. So either the docs might need a point or two of clarification or I sense this may be an edge case with `Props` and Slinky's reader/writer (unless I'm missing something, which won't surprise me!).

1. `columns` is expected to be an array of objects, so usually I would represent this in Slinky as `Seq[Column]`, but that results in `columns` being undefined! Curiously, if I follow the usual scalaJs approach of extending `js.Object` and make `Column` a `class` instead of a `case class`, it works. So does Slinky's reader/writer not apply in this example?:
```scala
class Column(
                    val filterable: Boolean,
                    val Header: String,
                    val accessor: String,
                    val show: Boolean
                 ) extends js.Object

@JSImport("react-table", JSImport.Default)
@js.native
object ReactTableLibrary extends js.Object

@react object ReactTable extends ExternalComponent {   

  implicit val metricsDecoder: Decoder[Column] = deriveDecoder
  implicit val metricsEncoder: Encoder[Column] = deriveEncoder

  val defaultData = convertJsonToJs(
    parse("""[{"test" : "value"}]"""
  ).right.get)

  val defaultColumns: js.Array[Column] = parse("""[  {    "filterable" : true,    "Header" : "Test",    "accessor" : "test",    "show" : true  }]""")
    .right.get.as[Seq[Column]].right.get.toJSArray

  case class Props(
                      data: js.Any = defaultData,
                      columns: js.Array[Column] = defaultColumns
                  )
  override val component = ReactTableLibrary
}
```

2. When I go to render this `ReactTable`, I cannot rely on the default `Prop` values. The best I can do is reference them redundantly in my render like:
```scala
@react object DataTable {
  case class Props(someProp: String)
  val component = FunctionalComponent[Props] { props =>
      ReactTable(
              data = ReactTable.defaultData,
              columns = ReactTable.defaultColumns
       )
    }
}
```

**Comment by shadaj** [comment]
So for the first issue, you'll need to define `Column` as a `case class` that doesn't extend `js.Object`. When the type is a `case class`, Slinky is able to inspect the contents to automatically convert to JS types. On the other hand, extending `js.Object` effectively tells Slinky to "back off" and assume that the value passed in is already a JS value.

The second issue looks like a bug, just to be sure the issue is that only the parameters show up and no default values are available?

**Comment by evbo** [comment]
For 1) are you saying I should use a `case class` in a certain way? I already tried that but it was interpreted as `undefined`. Extending `js.Object` was my second attempt _after_ trying to use a `case class`. So maybe would it help if I put together a minimal example? I won't be able to do this immediately, but let me know what would be helpful and I'll try to get to it.

For 2) correct: compilation fails (if I just do `ReactTable()`)saying I am missing required parameters, unless I explicitly reference the default values . I have since changed my code a lot, but if a minimal example for 1) is needed then 2) would be included with that when I get around to it.

**Comment by evbo** [comment]
@shadaj I think you've fixed issue 2 above. Thank you, Slinky `0.6.2` does not require me to explicitly call `Props`!

As for issue 1, there's still something awkward going on, but I'm not sure if it's a bug or a "feature". We can close this if it's an expected feature, otherwise is this bug?:

I've managed to use case classes, but with a couple of caveats. My suspicion is that [this framework](https://github.com/tannerlinsley/react-table/tree/v6) I'm using is expecting ReactComponent objects to be passed to it, specifically the object must have `Props`. Then, it passes the `Props` back to you so you can override behavior of the component with your own.

So here's the cleanest I've been able to implement that pattern in Slinky, with minimal scalajs types:

```scala
// create "imitation" react component Props, e.g.:
object FilterSetter {
   // these props will in turn be sent to me, allowing me to update the the table filter in the javascript library with new values
    case class Props(onChange: Seq[Double] => Unit)
  }

  object FilterGetter {
   // these props will in turn be sent to  me, allowing me to apply the filter from the table on the data
    case class Props(id: String, value: Seq[Double])
  }

// simplify calling these types. All that matters is the type is something called "Prop":
type FilterComponent = Row.FilterSetter.Props => ReactElement
type FilterMethod = (Row.FilterGetter.Props, Metrics) => Boolean
```

So far so good just using Scala objects, but then I then MUST define this as `js.UndefOr` (using option [fails to be recognized as the correct type in the framework](https://github.com/tannerlinsley/react-table/blob/v6/src/propTypes.js#L92)):

```
case class Column(
//                   Filter: Option[Row.FilterComponent] = None,
                   Filter: js.UndefOr[Row.FilterComponent] = js.undefined,
...
)
```


So not a big deal in the end, just need to use `js.UndefOr`. But, ideally no scalajs constructs would be needed!

**Comment by shadaj** [comment]
For `Option` vs `js.UndefOr`, `Option` is written as `null` for an empty value, whereas `js.UndefOr` is written as `js.undefined`. A few React libraries actually depend on getting `js.undefined` instead of `null`, which is what I think you're running into.

For the `type Metrics`, Slinky doesn't currently have a `Reader` for that type which is why it is just falling back to an opaque reader in this case. Pull requests are welcome if you'd like to fix this!

**Comment by evbo** [comment]
@shadaj is there a way to implicitly convert `Props` to a new case classes that uses `js.UndefOr` in place of `Option` type?

That would be slick, so I can keep Scala objects until the final conversion into javascript.

I'll look into `Reader` later on for `Map` type. I was confused because I thought it already existed. My example doesn't really care if it's `mutable.Map` or not. I just need a Scala type preferably and `mutable.Map` appears to convert automatically from `js.Dictionary` so I thought to use that instead of immutable.

**Comment by shadaj** [comment]
@evbo that's interesting. Looking at your PR, things should have "just worked" with the definitions picked up when deriving reader/writers for your props type. I wonder if this is some issue with variances. Will need to take a closer look at this.

I'm curious, why do you need a mutable map in this case? Behavior can be pretty odd here since modifying the map wouldn't modify the original JS dictionary.

**Comment by evbo** [comment]
@shadaj great question. The reason is because Scala.js implicitly converts mutable map to javascript Dictionary, and so for cases where a javascript library might pass a `Dictionary` and the `key` to access the value from, it's convenient to work directly with mutable map (than say to try and read the js object as a `case class` and then try `matching` the `key` to an appropriate attribute of the case class)

Here's an example on line 24 of where mutable map comes in handy when being passed `filter` (the key) and `row` (the dictionary): https://codesandbox.io/s/r40ovqp5jq

**Comment by evbo** [comment]
I am able to use default data in the props of my external components now, for instace:

```scala
@js.native
@JSImport("@atlaskit/popup", JSImport.Default)
private object AtlaskitPopup extends js.Object
@react object Popup extends ExternalComponent {
  override val component = AtlaskitPopup

 val defaultData = Seq(0, 8)

  case class Props(
                    onClose: () => Unit,
                    isOpen: Boolean,
                    content: () => ReactElement,
                    trigger: TriggerProps => ReactElement,
                    // number of pixels "along" and "away" from the target object
                    offset: Seq[Int] = defaultData,
                    zIndex: Int = 800,
                    placement: String = "bottom",
                    rootBoundary: String = "document"
                  )
}
```
