### ISSUE TITLE
Support for global state

### ISSUE THREAD

**Issue by bilal-fazlani** [shadaj/slinky#241]
Hi,
We are about to start developing our web applications in scalajs and are evaluating various react solutions for scala js. This library seems a very attractive solutions as it provide closest react api and syntax. I have tried using slinky for basic applications and my experience was very good.

When I tried to integrate [diode](https://diode.suzaku.io/), however, I ran into issues when trying to subscribe to global state from the component. These are some weird errors I could not understand. 
```
 "An undefined behavior was detected: Vector() is not an instance of java.lang.Integer"
```

I found that some other react libraries are compatible with global state, particularly with diode. Is it possible to use global state (either diode or something else) with slinky ? If yes, could you please share the approach?

**Comment by ryneflood** [comment]
I can't say that I know the solution to your exact issue, but I can say that I was able to successfully integrate Diode into a Slinky app (albeit, just a play-around project). I used a combination of Hooks + Context API to do so. Can't guarantee that it's the correct approach, but at least it _did_ work.

Let me know and I can share the project if that'll help out

**Comment by bilal-fazlani** [comment]
Thanks @ryneflood for the reply. It would be really great if you could share the project/details. Thanks!

**Comment by ryneflood** [comment]
https://github.com/ryneflood/slinky-diode-example

**Comment by ryneflood** [comment]
Tried to make it as minimal as possible; uses FunctionalComponents + Hooks, so there should be a properly-written version of those coming in a future Slinky release? I would assume the same/similar approach should work with a newer version of Slinky

**Comment by bilal-fazlani** [comment]
Thank you @ryneflood ! I will take a look at this

**Comment by ryneflood** [comment]
I _think_ everything should be pretty straightforward. But like I said I can't guarantee that's the ideal way to do things, I'm a bit of React noob as it is, but let me know if you have any questions in there

**Comment by shadaj** [comment]
Closing since this question appears to have been resolved!
