### ISSUE TITLE
Document how to use Aria tag

### ISSUE THREAD

**Issue by evbo** [shadaj/slinky#242]
I'm sure it's simple, but I'm stuck and banging my head! How can I say, e.g., a button has `aria-hidden = "true"`?

I figured it's something similar to one of these attempts:

```
button(className := "close", aria("hidden") := "true", onClick := toggleShowHidden _)(span("✖"))
button(className := "close", `aria-hidden` := "true", onClick := toggleShowHidden _)(span("✖"))
button(className := "close", aria-`hidden` := "true", onClick := toggleShowHidden _)(span("✖"))
```

But no, that's wrong... I know I could create a custom tag and it will certainly work. But something tells me I'd be reinventing the slinky if I did that!

Perhaps related to Props?: https://github.com/shadaj/slinky/issues/223

**Comment by shadaj** [comment]
Hi @evbo! It's `aria-"hidden"`! I'll keep this issue open as a reminder to check that this is documented.
