### ISSUE TITLE
Support use of children: Seq[ReactElement] within Props 

### ISSUE THREAD

**Issue by baank** [shadaj/slinky#245]
Currently only children: ReactElement* will be converted to a curried parameter.

The use of varargs is a problem as:
1) It forces children to be the last parameter.
2) It means you can't use default values for any of your parameters.

Allowing children: Seq[ReactElement] would solve these two problems.

**Comment by shadaj** [comment]
This may be a breaking change for users that are currently using `children: Seq[ReactElement]`, so targeting the 0.7.0 release.

**Comment by baank** [comment]
I just checked and this actually works. Closing.
