### ISSUE TITLE
Support triggering slinky html listeners programmatically (for unit testing)

### ISSUE THREAD

**Issue by evbo** [shadaj/slinky#249]
For my unit tests to trigger behavior of my components, I'd like to be able to programmatically trigger slinky event listeners as can be done with vanilla javascript:
https://stackoverflow.com/a/23612498/1080804
https://stackoverflow.com/a/42554283/1080804

However, in trying to follow those examples or this [react codepen](https://codepen.io/mayank_shubham/pen/evJaZV?editors=1111), change events only fire with direct interaction from the user, not with programmatically dispatched events:

```scala

// in rendering section of functionalComponent ...
val myInput: ReactRef[Element] = React.createRef[Element]
input(className := "form-control", ref := myInput, `type` := "number", onChange := handleChange _)

// in my handleChange function
val event = js.Dynamic.newInstance(js.Dynamic.global.CustomEvent)(
            "input",
            js.Dynamic.literal(bubbles = true)
          ).asInstanceOf[CustomEvent]
myInput.current.asInstanceOf[HTMLInputElement].dispatchEvent(event)
```

Or equivalently in chrome console:
```javascript
// get the component in the dom:
var myInput = document.evaluate('//*[@id="root"]/div/input',document,null,XPathResult.FIRST_ORDERED_NODE_TYPE).singleNodeValue
myInput.dispatchEvent(new CustomEvent("change"));
```

The above is correctly dispatching an event, but the callback defined in my slinky HTMLInputElement `input` never fires.

However, I can call an onchange if I set it not using slinky/react:

```javascript
var v = function(){console.log('FIRE')};
myInput.setAttribute("onchange", "v()");
myInput.dispatchEvent(new CustomEvent('change'));
```

[I see that react has it's own event for input changes](https://stackoverflow.com/a/42554283/1080804), `'input'`. Still I'm not able to trigger the `onChange` callback when dispatching `input` either.

Am I close? Or is the best way to do this by writing a facade for [ReactDom test utils](https://reactjs.org/docs/test-utils.html)?

**Comment by evbo** [comment]
[I see that react has it's own event for input changes](https://stackoverflow.com/a/42554283/1080804), `'input'`. Still I'm not able to trigger the `onChange` callback when dispatching `input` either.

**Comment by shadaj** [comment]
React actually has a bunch of quirks with how it listens to input events (see https://stackoverflow.com/questions/23892547/what-is-the-best-way-to-trigger-onchange-event-in-react-js). Writing a facade for the test utils would probably be the best path.

If you're interested in contributing a facade, I would be glad to merge it in to `slinky-web`!

**Comment by evbo** [comment]
yeah, but in addition to React event quirks, there's something else going on I think.


If I set a break point and capture the events that correctly fire (due to user input) and then try dispatching that same exact event, I get an expected result:

```javascript
var t = arg1$16.nativeEvent;
myInput.dispatchEvent(t);
VM1276:1 Uncaught DOMException: Failed to execute 'dispatchEvent' on 'EventTarget': The event is already being dispatched.
```

If I then let the debugger continue so that the event fully fires, I once again dispatch the event just like before but nothing happens this time. So this tells me that I'm dispatching events that are being recognized by react, but still it's unclear why they would only be detected if they are duplicate events. 

Do you have any recommendations for how I could take this test a step further with lower level Slinky event handling?

**Comment by evbo** [comment]
You're right, the react event system is very tricky to understand and the stackoverflow posts only scratch the surface!

It probably would have been a better use of my time figuring out a facade for test utils, but I was lazy and wrote a quick facade for a _much_ simpler alternative

```
@js.native
@JSImport("react-trigger-change", JSImport.Default)
class ReactTriggerChange(val node: js.Object) extends js.Object

object ReactTestEvent {
  def trigger(node: js.Object) = {
    new ReactTriggerChange(node)
  }
}
```


At least for now it works for my needs, but I'll likely consider test utils in the future

**Comment by evbo** [comment]
@shadaj I'm fine having this issue closed unless you feel Implementing test utils is a feature enhancement that applies to Slinky necessarily.

Also, the work around I've posted above gets the job done. Maybe not for all, but at least it's light weight.

**Comment by shadaj** [comment]
Yes, don't think we need a test utils within Slinky core, that would make more sense as a separate library.
