### ISSUE TITLE
Include CSS, React, Stdlib definitions

### ISSUE THREAD

**Issue by baank** [shadaj/slinky#252]
It's common when creating wrappers for existing libraries to need type definitions.

This project has a few that would be useful to include in Slinky:

https://github.com/oyvindberg/ScalablyTyped/tree/master/c/csstype
https://github.com/oyvindberg/ScalablyTyped/tree/master/r/react
https://github.com/oyvindberg/ScalablyTyped/tree/master/s/std

**Comment by shadaj** [comment]
As discussed in the Gitter channel, the plan is to not have Slinky directly depend on these type definitions, but instead to have ScalablyTyped have a compat layer with Slinky.
