### ISSUE TITLE
Intellij 2019.1 doesn't request for Slinky support

### ISSUE THREAD

**Issue by mt40** [shadaj/slinky#273]
Hi, I'm using IntelliJ 2019.1.1 on MacOS and use [Create React Scala app template](https://github.com/shadaj/create-react-scala-app.g8). I follow the instruction in https://slinky.dev/docs/installation/ to get IntelliJ to recognize `@react` macro but IntelliJ never shows a popup to ask me to enable Slinky support.

Is there any extra steps that I need to take to make this work?

**Comment by zhy0216** [comment]
i figured this out by adding 
`libraryDependencies += "me.shadaj" %% "slinky-core-ijext" % slinkyVersion`

**Comment by mt40** [comment]
Yup, it works if I manually add the jar or add the dependency like you. But maybe there is something prevents IntelliJ from automatically identifying Slinky support

**Comment by shadaj** [comment]
This is interesting, IntelliJ should have automatically picked up the extension from the included JSON file. Will take a look into this to see if maybe the configuration style has changed.

**Comment by shadaj** [comment]
Just tested this today, and IntelliJ correctly detected the support plugin. Closing for now since this appears to be fixed.

**Comment by AlexITC** [comment]
Hi, I'm experiencing the same problem:
![Screenshot from 2020-06-23 15-07-02](https://user-images.githubusercontent.com/4218436/85462875-38597d00-b563-11ea-9d8b-2e7936767288.png)

**Comment by evbo** [comment]
Same here with version 2020.2.

@shadaj I pulled your g8 example just to be sure it wasn't something odd about my sbt project. What 2020 version of intellij do you use that works with the Slinky extension?


Thanks!
