### ISSUE TITLE
js.Object conversion of Props in FunctionalComponent?

### ISSUE THREAD

**Issue by evbo** [shadaj/slinky#281]
Hi, I have a hacky work around for [javascript libraries](https://refreshless.com/nouislider/) that require the props to be sent to the library, with the actual element embedded as a `ref` inside a `div`. What this means is the `Props` containing arguments for the js library need to be sent to javascript as a `js.Object`, not a `case class`.

So I am wondering if there's a cleaner syntax Slinky can/already support to allow me to pass the `Props` object as a `js.Object`?

I've already looked into converting a `case class` into a `js.Object`, but the [posted solutions](https://stackoverflow.com/questions/35847332/best-way-to-convert-a-case-class-to-a-js-object) vary in feasibility and don't work in my case.

The cleanest solution I've come up with is define my `Props` for my `FunctionalComponent` as a regular class that extends `js.Object`.

This allows me to pass props to the `FunctionalComponent`, and when the ref needs to get rendered, it has the `js.Object` it needs to instantiate the library (no additional conversion needed)! But that means I'm not working with regular `Scala` objects...

For instance, the nouislider library linked above requires `useEffect` to [reinstantiate the slider on every update](https://github.com/mmarkelov/react-nouislider/blob/56e8c42e67226ae26a5a0b6377508ab4f4c101c3/src/index.js#L97-L104):

```
@JSImport("nouislider", JSImport.Default)
@js.native
object NoUiSlider extends js.Object {
  def create(container: Element, props: js.Object): js.Object = js.native
}

...

// here the "container" is the ref attached to the div where this slider is embedded
NoUiSlider.create(container.current, props)

...

div()(
          div(ref := container)
)
```

So the problem is, if my Props are a `case class` everything works until I call `create`, which can't find the fields of my `Props`

So is there a clean way in slinky to get the raw json object of `Props` in addition to the case class? That way I pass the `js.Object` to `create`, but use the `case class` for my `FunctionalComponent` otherwise.

**Comment by shadaj** [comment]
This is exactly what `Writer` is for! You can derive a `Writer[T]` for your props type, and then can use that instance to convert the Scala object to a `js.Object` when you need to talk to the library.

**Comment by evbo** [comment]
@shadaj thanks for the hint, and [thanks for your unit tests](https://github.com/shadaj/slinky/blob/8899ac4ebea298970dd2cf9e5d765276ec252826/tests/src/test/scala/slinky/core/ReaderWriterTest.scala#L121-L131)!

Fixing this was too easy!:
`NoUiSlider.create(container.current, implicitly[Writer[Props]].write(props))`

Slinky is very powerful, thank you!
