### ISSUE TITLE
How to configure for scala on the server side?

### ISSUE THREAD

**Issue by yatesco** [shadaj/slinky#292]
<newbie/> I hope you don't mind me asking here, but how would I go about using slinky in a project that also contained server-side Scala and some Scala that was shared between the two.

If I have:
```
- build.sbt
- shared/src
- server/src
- client/src
```
then I need to configure slinky in the `client` directory, but I am missing something silly and can't quite figure it out.

My question isn't how to handle modules within a Scala project, it is more how do I configure Slinky to live in `client` whilst also accessing shared. And where would I run the web tools (npm etc.) from - the root or the client?

Many thanks!

**Comment by ramnivas** [comment]
Hey @yatesco!

Here is a guide that you can follow: https://www.scala-js.org/doc/project/cross-build.html. Then you can add Slinky (and any other JS-only dependencies) under `jsSettings`.

**Comment by yatesco** [comment]
Thanks Buddy.

**Comment by shadaj** [comment]
Closing since this appears to be resolved!
