### ISSUE TITLE
Comparison to other scalajs react adaptions

### ISSUE THREAD

**Issue by phdoerfler** [shadaj/slinky#298]
I would greatly appreciate it if someone could say how this library compares to [japgolly/scalajs-react](https://github.com/japgolly/scalajs-react).

What do both libraries different, how are they similar, what's their focus, and so on. Thanks!

Also see:
https://github.com/japgolly/scalajs-react/issues/581

**Comment by evbo** [comment]
duplicate issue here: https://github.com/shadaj/slinky/issues/210
