### ISSUE TITLE
NoSuchFileException on .slinkyPluginIC

### ISSUE THREAD

**Issue by Jake6329** [shadaj/slinky#300]
I cloned the whole repository in my local machine and opened the project with IntelliJ. But when I import the sbt definition, I get an error saying this:

    (coreIntellijSupport / intellijPluginJars) java.nio.file.NoSuchFileException: /Users/jakelim/.slinkyPluginIC/sdk/192.6817.14/plugins

Obviously, it's looking for some files under my home directory, so I created an empty directory at `/Users/jakelim/.slinkyPluginIC/sdk/192.6817.14/plugins`, but then I get a different error message:

    (coreIntellijSupport / intellijPluginJars) org.jetbrains.sbtidea.download.LocalPluginRegistry$MissingPluginRootException: Can't find plugin root for org.intellij.scala: check plugin name

Anyone any idea on how one would resolve this issue?

I'm using IntelliJ version 2019.2.3 community edition

**Comment by shadaj** [comment]
You could try running `sbt coreIntellijSupport/updateIntellij` before importing, which will download the IntelliJ files for the plugin subproject. My guess is that the IntelliJ plugin doesn't automatically download the files when SBT requests the classpath.

**Comment by Jake6329** [comment]
@shadaj Thanks. It solved my problem.
