### ISSUE TITLE
Can't I use defaultProps ?

### ISSUE THREAD

**Issue by steelbluelee** [shadaj/slinky#301]
I'm trying to use defaultProps in slinky Component. But I cannot. So, I write the following code which
operates. But It doesn't seem good. What could I do?

```
object HelloName {
  @react private class HelloNameInner extends StatelessComponent {
    case class Props(name: String)

    def render(): ReactElement = {
      h1(s"hello ${props.name}")
    }
  }

  def apply(name : String = "default_name"): ReactElement = {
    HelloNameInner(name = name)
  }
}
```

**Comment by shadaj** [comment]
You can get default props in Slinky by specifying default values for the parameters in `Props`! So something like `case class Props(name: String = "default_name")` would work.

**Comment by steelbluelee** [comment]
Good.

Thx.
