### ISSUE TITLE
scala 2.13 slinky-core-ijext

### ISSUE THREAD

**Issue by user753** [shadaj/slinky#312]
```
libraryDependencies += "me.shadaj" %%% "slinky-core-ijext" % "0.6.3"
```

> not found: https://repo1.maven.org/maven2/me/shadaj/slinky-core-ijext_sjs0.6_2.13/0.6.3/slinky-core-ijext_sjs0.6_2.13-0.6.3.pom

**Comment by shadaj** [comment]
If you need to add it to the classpath, only two `%%` should be used. Does IntelliJ not pick up the extension automatically for you?

**Comment by user753** [comment]
>If you need to add it to the classpath, only two %% should be used

Didn't help. Are you sure there is a 2.13 version? 
https://mvnrepository.com/artifact/me.shadaj/slinky-core-ijext
shows only 2.12

**Comment by shadaj** [comment]
@user753 ah, yeah, there's no 2.13 version since the Slinky macro works the same for 2.12/2.13. You can use `libraryDependencies += "me.shadaj" % "slinky-core-ijext_2.12" % "0.6.3"`
