### ISSUE TITLE
Not working with SJS 1.0

### ISSUE THREAD

**Issue by Katrix** [shadaj/slinky#332]
Getting a `TypeError: class constructors must be invoked with 'new'` error if I try to use SJS 1.0. Goes away if I switch back to 0.6.

**Comment by shadaj** [comment]
Could you share a minimal reproduction of the error? Also, if you disable hot-reloading, which appears to be broken with Scala.js 1.0 (as per #331), do things work then?

**Comment by Katrix** [comment]
Got the error on roughly a copy of the getting started seed.

**Comment by shadaj** [comment]
@Katrix alright, thanks for the info! Will look into this over the weekend. In the meantime, could you try with ES6 output disabled?

```scala
scalaJSLinkerConfig ~= { _.withESFeatures(_.withUseECMAScript2015(false)) }
```

I have a hunch that this may be related.

**Comment by sbrunk** [comment]
I just ran into the same error. Disabling ECMAScript2015 as described by @shadaj above (in conjunction with a `sbt clean`) did help in my case.

The error seems to caused by this call:
https://github.com/shadaj/slinky/blob/1a99b52cf3e67d8aad13254752a973def941de44/core/src/main/scala/slinky/core/BaseComponentWrapper.scala#L189

**Comment by sbrunk** [comment]
Forgot to mention that the error still occured after disabling/working around the hot encoding issue #331 so it seems unrelated to that one.

**Comment by shadaj** [comment]
Thanks for the info @sbrunk! Looks like we're running into the issue described at https://stackoverflow.com/questions/30689817/es6-call-class-constructor-without-new-keyword. The immediate solution would be to use ES6 proxies, but I'm a bit concerned about the performance impact so going to do a bit more research before committing to a specific fix.

**Comment by shadaj** [comment]
Was able to fix this without any proxies involved, PR open at #332!
