### ISSUE TITLE
Ensure compatibility with latest IntelliJ

### ISSUE THREAD

**Issue by shadaj** [shadaj/slinky#357]
IntelliJ 2020 is out, so we need to check that the support plugin is still functioning correctly there. I've been using Metals recently, so help from any community members using IntelliJ would be greatly appreciated!

**Comment by dispalt** [comment]
Im going to take a look right now.

**Comment by dispalt** [comment]
So it looks like some binary compat issue was breaking nightlies for 2020.1.x but it should be fixed now.

If you saw this in your idea.log

```
2020-05-19 20:04:34,709 [ 108734]  ERROR - aemon.impl.PassExecutorService - Plugin to blame: Scala version: 2020.1.1174 
2020-05-19 20:04:34,709 [ 108734]  ERROR - aemon.impl.PassExecutorService - 'org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.MixinN
odes$Map org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.TypeDefinitionMembers$.getTypes(com.intellij.psi.PsiClass)' 
java.lang.NoSuchMethodError: 'org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.MixinNodes$Map org.jetbrains.plugins.scala.lang.psi.i
mpl.toplevel.typedef.TypeDefinitionMembers$.getTypes(com.intellij.psi.PsiClass)'
        at slinky.core.SlinkyInjector.createComponentBody(SlinkyInjector.scala:19)
```

this should be fixed soon per one of the developers on the `intellij-scala` team.

**Comment by shadaj** [comment]
Thanks for investigating @dispalt! That's good to hear that things will be fixed in an upcoming release.

**Comment by shadaj** [comment]
IntelliJ compatibility appears to be resolved, there are still a few issues with plugin detection, but that's an independent issue so closing.
