### ISSUE TITLE
Props with Type Parameters

### ISSUE THREAD

**Issue by schwepp** [shadaj/slinky#40]
How can I use Props with type parameters?

For example

```scala
@react class Example extends Component {

  case class Props[T](data: Seq[T])

  type State = Unit

  def initialState = ()

  def render() = ???
}
```

will just result in the following errors:

```
[error] <macro>:3: class Props takes type parameters
[error]     type Props = Example.Props
[error]                          ^
[error] <macro>:13: could not find implicit value for parameter propsReader: me.shadaj.slinky.core.Reader[example.Example.Props]
[error]     @__SJSDefined class Def(jsProps: scala.scalajs.js.Object) extends Definition(jsProps) {
[error]                                                                       ^
[error] <macro>:17: overloaded method value apply with alternatives:
[error]   [T](data: Seq[T])me.shadaj.slinky.core.KeyAndRefAddingStage[example.Example.Def] <and>
[error]   (p: example.Example.Props)(implicit propsWriter: me.shadaj.slinky.core.Writer[example.Example.Props], implicit constructorTag: scala.scalajs.js.ConstructorTag[example.Example.Def])me.shadaj.slinky.core.KeyAndRefAddingStage[example.Example.Def]
[error]  cannot be applied to (example.Example.Props[T])
[error]     def apply[T](data: Seq[T]): me.shadaj.slinky.core.KeyAndRefAddingStage[Def] = this.apply(Props.apply[T](data))
[error]                                                                                        ^
[error] three errors found

```

**Comment by shadaj** [comment]
Hi @kiw-i! Do you have a use-case for where you would need a type parameter in `Props`? I'm not super sure what it would mean conceptually for props to take a type parameter.

**Comment by kiw-i** [comment]
Thank you for your quick response,

I'm playing around with React Native (which works good so far).

But for the `FlatList` component for example, I think I need something like this

```scala
@react object FlatList extends ExternalComponent {

  @js.native
  trait Item[T] extends js.Object {
    val index: Int = js.native
    val item: T = js.native
  }

  case class Props[T](
    data: Seq[T],
    renderItem: Item[T] => ReactElement,
    keyExtractor: (Int, T) => String
  )

  @js.native
  @JSImport("react-native", "FlatList")
  object Component extends js.Object

  val component = Component
}
```

Do you have any idea how this could be implemented?

**Comment by shadaj** [comment]
Yeah, that makes sense for why you would need a type parameter. Something you could try would be to make the `Props` inside the component untyped so:
```scala
case class Props(data: js.Object, renderItem: js.Object, keyExtractor: js.Object)
```

And then you could drop the `@react` annotation and instead have a custom `apply` that takes a type parameter and implicit readers and writers for it and calls apply with the untyped `Props`:
```scala
def apply[T](data: Seq[T], renderItem: Item[T] => ReactElement, keyExtractor: (Int, T) => String)(implicit reader: Reader[T], writer: Writer[T]) = {
  apply(Props(
    implicitly[Writer[Seq[T]]].write(data),
    implicitly[Writer[Item[T] => ReactElement]].write(renderItem),
    implicitly[Writer[(Int, T) => String]].write(keyExtractor)
  ))
}
```

**Comment by schwepp** [comment]
Thank you, that will work for me.

**Comment by shadaj** [comment]
Hi @schwepp! I've been looking into adding official React Native support for Slinky, and was wondering if you could share your set-up. A Hello World example would be perfect.

**Comment by schwepp** [comment]
Hi, great you are interested.
It's not yet done but I'm still working on React Native support. Mainly a Scala source generator for React Native Componets which fetches the definitions from the Docs, similar to the TagComponent generator.
There are some issues though, I would like to do a pull request when it's done :)

As for an example project, there is not much to do but I will upload one when I have some time tomorrow so you can check it out.

**Comment by schwepp** [comment]
Hi @shadaj, sorry for the long delay, but you can check out a basic example now [here](https://github.com/schwepp/slinky-native-example). 
I used scalajsTransformer from SRI, but maybe [Haul](https://github.com/callstack/haul) could be used for Webpack/ScalaJSBundler integration.
