### ISSUE TITLE
Events from inputs seem to be mutable

### ISSUE THREAD

**Issue by AlexITC** [shadaj/slinky#409]
From the main [website](https://slinky.dev/), on the ToDo app, you see this code to handle the changes from an input element:

```
  def handleChange(e: SyntheticEvent[html.Input, Event]): Unit = {
    val eventValue = e.target.value
    setState(_.copy(text = eventValue))
  }
```

I'd expect that calling `setState(_.copy(text = e.target.value))` would work but it doesn't, leading to a `NullPointerException` because `target` is null.

From what I understand, it happens because the event `e` is a JavaScript object that's mutated when the event handler finishes, and when react ends up invoking the inner function set the actual, such event has already been mutated.

I haven't seen this behavior being documented on the docs but it's a tricky one, is there any chance to avoid it?

Thanks.

**Comment by ramnivas** [comment]
I believe this will be a non-issue in React 17, per https://reactjs.org/blog/2020/08/10/react-v17-rc.html#no-event-pooling

**Comment by AlexITC** [comment]
Looks like it will, is it safe to use React 17 with Slinky 0.6.5?

Thanks.

**Comment by shadaj** [comment]
React 17 should work fine, Slinky doesn't depend on any of the changed APIs.
