### ISSUE TITLE
Add a Resource Page to the Documentation

### ISSUE THREAD

**Issue by pme123** [shadaj/slinky#436]
When starting with Slinky it was hard to find examples, talks etc..

Is it possible to add a page to the documentation, that contains:

- Blog Articles
- Talks
- Blog Articles
- Cheat Sheet
- Sample Projects
- Projects using Slinky

I took it from here (A great example):
https://zio.dev/docs/resources/resources

I would be happy to create the first version of such a page.

**Comment by shadaj** [comment]
This is a great idea! A PR to add an initial version of a resources page would definitely be welcome!
