### ISSUE TITLE
Allow multiple TagMods  to be passed as object like in some js libraries?

### ISSUE THREAD

**Issue by evbo** [shadaj/slinky#454]
Consider how tags are passed by destructuring a js object here: https://github.com/tannerlinsley/react-table/blob/master/examples/basic/src/App.js#L54

To implement this in Slinky (Scala), I'm simply writing a facade extending js.Object and then manually setting TagMod for each field. But this js.Object is completely defined by the javascript API, so there's no type-safety or functional benefit to defining it in scala (I trust the libraries unit tests are sufficient!).

Is there any way of dynamically passing an object with "key" names that refer to individual TagMods and with "values" that define the Tag value? My intent is to closely match the javascript API, but if there's a simple pattern I'm forgetting for how to do this in scala that would be good too!

**Comment by shadaj** [comment]
Right now, you could use a `CustomTag` for the individual keys to convert the dictionary into a list of `TagMod`s. It's possible the performance might not be as great though (really depends on how much inlining Scala.js does), so if you find that it's too slow it might make sense to explore a specific API for this situation.

**Comment by evbo** [comment]
fair enough and good point about performance. This was mostly out of curiosity so the nature of this issue is fulfilled I think!
