### ISSUE TITLE
Scala3 Migration Strategy

### ISSUE THREAD

**Issue by sidnt** [shadaj/slinky#461]
Setting up this issue to track the migration of slinky to scala3. Is there a draft WIP in somewhere that could be looked at?

**Comment by psylinse** [comment]
I'm curious if this is on the table for slinky. I'm looking at starting a new project in scalajs and would love to know if this is something you all are tracking. No worries if it's not in the plans, just gathering info!

**Comment by Voronar** [comment]
What do you think about tags building with https://dotty.epfl.ch/docs/reference/contextual/context-functions.html#example-builder-pattern?

**Comment by godenji** [comment]
> What do you think about tags building with https://dotty.epfl.ch/docs/reference/contextual/context-functions.html#example-builder-pattern?

[Shaka](https://github.com/getshaka-org/shaka) uses Scala 3 builder pattern, could look at that for inspiration.

**Comment by povder** [comment]
Draft PR https://github.com/shadaj/slinky/pull/494
