### ISSUE TITLE
mill and esbuild - node modules not imported 

### ISSUE THREAD

**Issue by dkirchhof** [shadaj/slinky#498]
Hello,  
i'm trying to use slinky with `mill` and `esbuild`. Well, there is not much i have done so far and i have virtually no experience with scalajs.  
You mentioned in your documentation that react could be imported as CommonJS module. Actually after compiling the scala files to js, there is no "require" or "import" for the react or react-dom module. It refers to global objects. Accordingly esbuild can't bundle all the stuff and i will get an error like `ReactDOM is not defined` in the browser.  
All js dependencies like react and esbuild were added via yarn / npm.

build.sc:
```scala
import mill._, scalalib._, scalajslib._

object Client extends ScalaJSModule {
  def scalaVersion = "2.13.6"
  def scalaJSVersion = "1.7.0"
  def ivyDeps = Agg(
    ivy"me.shadaj::slinky-core_sjs1:0.6.7+9-14b24223",
    ivy"me.shadaj::slinky-web_sjs1:0.6.7+9-14b24223",
  )
}
```

Hello.scala
```scala
package main.scala.hello

import org.scalajs.dom._
import slinky.core._
import slinky.web.ReactDOM
import slinky.web.html._
import scala.scalajs.js.annotation.JSImport
import scala.scalajs.js.native
import scala.scalajs.js.Object
import scala.scalajs.js.native
import scala.scalajs._

// @JSImport("react-dom", JSImport.Default)
// @JSImport("react-dom", JSImport.Namespace, "ReactDOM")
// @JSImport("react-dom", JSImport.Default, "ReactDOM")
// @js.native
// object ReactDOM extends js.Object {
//  def render (a: AnyVal, b: AnyVal): AnyVal = js.native
// }


object Hello extends App {
  // ReactDOM.render(
  //   h1("hello world"),
  //   document.getElementById("app")
  // )

  println(ReactDOM)
}
```
(As you can see, i tryed to create my own facade without a fallback value, but it will produce a linking error)
 

```sh
> mill Client.fastOpt
> ./Client/node_modules/.bin/esbuild ./out/Client/fastOpt/dest/out.js --bundle --outfile=./bundle.js
```

I could import react as a global object in my html file via cdn, but i don't want to create these workarounds at this early stage.

**Comment by shadaj** [comment]
I believe you may need to pass in some special options to Mill to request a CommonJS output (Scala.js supports many output formats).

**Comment by dkirchhof** [comment]
Thanks for the advice. Now i found a hint in the changelog of mill that there is a setting for it. I will try it out and can hopefully close the issue.

https://github.com/com-lihaoyi/mill/pull/212
