### ISSUE TITLE
react native fast refresh not working

### ISSUE THREAD

**Issue by joprice** [shadaj/slinky#537]
When I run `fastLinkJS`, I see the refreshing banner appear, but no change is picked up in the UI. I am using slinky `0.7.0` along with react native `0.66.4`.

**Comment by shadaj** [comment]
Thanks for the report! I wonder if React Native moving to the native fast refresh support has broken something. We only support hot reloading for class components using the old method right now.

**Comment by shadaj** [comment]
This may be fixed by #588, could you give it a try with the latest preview build?

**Comment by shadaj** [comment]
Closing for now, feel free to bump this if things are still broken!
