### ISSUE TITLE
Scala3 doesn't work with slinky-hot in some cases

### ISSUE THREAD

**Issue by AlexITC** [shadaj/slinky#547]
It is common to see this piece of code in Slinky projects, unfortunately, this causes problems with Scala3, the website doesn't load at all:

```
    if (LinkingInfo.developmentMode) {
      hot.initialize()
    }
```

**Comment by shadaj** [comment]
@AlexITC do you see any crashes in the console? There shouldn't be anything Scala 3 specific in the hot-reloading implementation.

**Comment by AlexITC** [comment]
I was able to isolate the problem, which occurs when rendering this [ErrorBoundaryComponent](https://github.com/wiringbits/wiringbits-webapp-utils/blob/master/slinky-utils/src/main/scala/net/wiringbits/webapp/utils/slinkyUtils/components/core/ErrorBoundaryComponent.scala):

```
Uncaught org.scalajs.linker.runtime.UndefinedBehaviorError: java.lang.ClassCastException: undefined is not an instance of slinky.readwrite.Reader
```

If I remove that, hot-reloading works.
