### ISSUE TITLE
Documentation on using JS React Hooks

### ISSUE THREAD

**Issue by nadenf** [shadaj/slinky#556]
It is not that clear how to use external JS React Hooks such as: [url-double-click](https://opensourcelibs.com/lib/use-double-click).

It would be good to add documentation [here](https://slinky.dev/docs/functional-components-and-hooks/). In particular around how to pass Refs to JS React Hooks.

**Comment by evbo** [comment]
Not sure if I'm oversimplifying this, but I've found external hooks to be pretty similar to writing facades as with other external js libraries. For instance, the popular QuillJS rich text editor is a simple one that involves refs too:

```scala
class UseQuill(val quill: js.UndefOr[Quill], val quillRef: ReactRef[Any]) extends js.Object

@js.native
@JSImport("react-quilljs", "useQuill")
object useQuill extends js.Function0[UseQuill] {
  override def apply(): UseQuill = js.native
}
```

**Comment by evbo** [comment]
I think it can be as simple as above based on how hooks are implemented as just simple functions. For instance, here are some custom hooks that are quite simple:

https://github.com/payalabs/use-slinky-hooks/blob/master/src/main/scala/com/payalabs/slinky/hooks/GenericHooks.scala
