### ISSUE TITLE
Support svg or arbitrary tags and attributes

### ISSUE THREAD

**Issue by evbo** [shadaj/slinky#582]
Hi! I was getting ready to submit a PR for expanding `html.json` but then I thought, was this file intentionally incomplete? Would it kill compile time of Slinky projects if this file included full `svg` support?

If no, then I'll submit my PR and close this.

If yes, then would it make sense to have a custom editable `html.json` where the user can add additional definitions they need?

# major use case:

TailwindCSS! I'd like to define a custom Progress Bar like shown here but lack the tags/attributes needed in Slinky:
[Circular progress bar](https://tailwindcomponents.com/component/circular-progress-bar)

Tailwind is growing in popularity and for good reason, so naturally other Slinky users would appreciate more tag/attributes support too?!

**Comment by shadaj** [comment]
Hmm, what do you seem to be missing for SVG? Slinky intentionally has separate HTML vs SVG tag definitions because some tags overlap but have different attributes depending on whether you are in HTML mode or SVG mode.

**Comment by evbo** [comment]
@shadaj sorry! I switched to Scala3 and the intelliJ intellisense is struggling to work! So I did not notice you keep svg in a separate module since I'm intelliSense-blind!  :face_with_spiral_eyes:
