### ISSUE TITLE
[Q] @react Component syntax

### ISSUE THREAD

**Issue by sonhanguyen** [shadaj/slinky#92]
This bugs me even though just a small thing. Is it possible to not have to repeat ourselves? I'm talking about going with either inheritance or annotation and not having to do both? What does the `@react` annotation give us just out of curiosity?

**Comment by ramnivas** [comment]
`@react` helps to remove some of the boilerplate that would be otherwise needed. Essentially, given the following code:

```scala
@react class HelloMessage extends Component {
  case class Props(name: String)

  override def render(): ReactElement = {
    div("Hello ", props.name)
  }
}
```

The macro behind `@react` translates it into the logical equivalent of the following:
```scala
object HelloMessage extends ComponentWrapper {
  case class Props(name: String)
  type State = Unit

  class Def(jsProps: js.Object) extends Definition(jsProps) {
    override def render(): ReactElement = {
      div("Hello ", props.name)
    }
  }

  def apply(name: String) = 
     apply(Props(name))
}
```

For React 16, it takes care of more things such as properly taking care of `componentDidThrow`.

**Comment by sonhanguyen** [comment]
in that case, would it be it cleaner/possible to just have to do `@react class HelloMessage { /*...*/ }` without `extends Component`? is there any other super class like `PureComponent`? can they be implemented as a macro too?

**Comment by ramnivas** [comment]
That would be possible, but then the IDE won't give code completion help. For example, with `extends Component`, you can have the IDE help you override, say, `componentDidMount` with the right signature.

**Comment by shadaj** [comment]
Closing as this question was resolved. Feel free to re-open if you have more!
